# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def generic_pods
    pod 'Alamofire', '~> 4.4' #Networking Library
    pod 'AlamofireImage'
    pod 'SkeletonView'
end

target 'SNY' do
    generic_pods
end
