# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def generic_pods
    
    # Networking Library
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage'
    
    # UI
    pod 'SkeletonView'
end

target 'SNY' do
    generic_pods
end
